project:
  type: website
  output-dir: docs
  
execute:
  freeze: auto

website:
  title: "MoveSIN"
  favicon: images/logo.png
  page-navigation: true
  back-to-top-navigation: true
  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: posts.qmd
      # - about.qmd
      
    right:
    - icon: github
      href: https://github.com/MoveSIN/website
    - text: "Bluesky"
      href: https://bsky.app/profile/ausmovementecology.bsky.social
      
      
  page-footer:
    background: light
    center:
      - icon: github
        href: https://github.com/MoveSIN/website
      - text: "Bluesky"
        href: https://bsky.app/profile/ausmovementecology.bsky.social
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



